cc_library(
    name = 'unwind',
    prebuilt=True,
)

cc_library(
    name = 'unwind-x86_64',
    prebuilt=True,
)

cc_library(
    name = 'unwind-elf64',
    prebuilt=True,
)

cc_library(
    name = 'unwind-ptrace',
    prebuilt=True,
)

cc_library(
    name = 'unwind-setjmp',
    prebuilt=True,
)
