cc_library(
    name = 'gflags',
    srcs = [
        'gflags.cc',
        'gflags_reporting.cc',
        'gflags_completions.cc',
    ],
    incs = ['.', '../include/gflags/'],
    deps = '#pthread',
    warning = 'no'
)
